In [16]:
import pandas as pd

In [17]:
dict_data = {
    "c1": ["a", "a", "b", "a", "b"], 
    "c2": [1, 1, 1, 2, 2], 
    "c3": [1, 1, 2, 2, 2]
}
df = pd.DataFrame(dict_data)
df

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [18]:
df.duplicated()

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [19]:
df.duplicated(keep="last")

0     True
1    False
2    False
3    False
4    False
dtype: bool

In [20]:
df.duplicated(keep=False)

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [21]:
df["c2"].duplicated()

0    False
1     True
2     True
3    False
4     True
Name: c2, dtype: bool

In [22]:
df.duplicated(subset=["c2"])

0    False
1     True
2     True
3    False
4     True
dtype: bool

In [23]:
# 중복 데이터 제거 

df

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [24]:
df.duplicated()

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [25]:
df2 = df.drop_duplicates()
df2

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [26]:
df3= df.drop_duplicates(keep="last")
df3

  c1  c2  c3
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [27]:
df4 = df.drop_duplicates(keep=False)
df4

  c1  c2  c3
2  b   1   2
3  a   2   2
4  b   2   2

In [28]:
df

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [29]:
df5= df.drop_duplicates(subset=["c2", "c3"])
df5

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2

In [31]:
df.drop_duplicates(subset=["c2", "c3"], keep=False)

  c1  c2  c3
2  b   1   2

In [32]:
df = pd.read_csv("./data/auto-mpg.csv", header=None)

df.columns = ["mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration",
              "model year", "origin", "name"]

df.head(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite

In [33]:
mpg_to_kpl = 1.60934 / 3.78541
df['kpl'] = df['mpg'] * mpg_to_kpl
df.head(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name,kpl
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu,7.652571
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320,6.377143
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite,7.652571

In [34]:
df['kpl'] = df['kpl'].round(2)

df.head(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name,kpl
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu,7.65
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320,6.38
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite,7.65

In [35]:
df = pd.read_csv('./data/auto-mpg.csv', header=None)

df.columns = ['mpg','cylinders','displacement','horsepower','weight',
              'acceleration','model year','origin','name'] 

print(df.dtypes)

mpg             float64
cylinders         int64
displacement    float64
horsepower          str
weight          float64
acceleration    float64
model year        int64
origin            int64
name                str
dtype: object

In [36]:
print(df['horsepower'].unique())

<ArrowStringArray>
['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0', '225.0',
 '190.0', '170.0', '160.0', '95.00', '97.00', '85.00', '88.00', '46.00',
 '87.00', '90.00', '113.0', '200.0', '210.0', '193.0',     '?', '100.0',
 '105.0', '175.0', '153.0', '180.0', '110.0', '72.00', '86.00', '70.00',
 '76.00', '65.00', '69.00', '60.00', '80.00', '54.00', '208.0', '155.0',
 '112.0', '92.00', '145.0', '137.0', '158.0', '167.0', '94.00', '107.0',
 '230.0', '49.00', '75.00', '91.00', '122.0', '67.00', '83.00', '78.00',
 '52.00', '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
 '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0', '108.0',
 '68.00', '58.00', '149.0', '89.00', '63.00', '48.00', '66.00', '139.0',
 '103.0', '125.0', '133.0', '138.0', '135.0', '142.0', '77.00', '62.00',
 '132.0', '84.00', '64.00', '74.00', '116.0', '82.00']
Length: 94, dtype: str

In [37]:
import numpy as np

In [38]:
df['horsepower'] = df['horsepower'].replace('?', np.nan)     
df = df.dropna(subset=['horsepower'], axis=0)    
df['horsepower'] = df['horsepower'].astype('float')           

print(df['horsepower'].dtypes)

float64